spring:
  application:
    name: api-data-v1
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
  webflux:
    base-path: /api/data-v1
server:
  port: 8081